:: Native win-arm64 test script for the python-feedstock.
::
:: The win-arm64 packages are cross-compiled on win-64 runners, so conda-build
:: is invoked with --no-test there and the recipe test section never runs.
:: This script replicates the `# [win]` test commands from recipe/meta.yaml
:: (outputs `python` and `libpython-static`) so they can be executed on a
:: native ARM64 Windows runner against the already-built packages.
::
:: Keep this in sync with the test sections of meta.yaml next to this file.
::
:: This lives under recipe/ rather than .scripts/ because .scripts/ is
:: regenerated by `conda smithy rerender` (and is git-ignored at the root).
::
:: Expected to be run inside an activated test environment, e.g.
::   micromamba run -p D:\test-env cmd /c recipe\test_win_arm64.bat
::
:: INPUTS (environment variables)
:: CONDA_PREFIX:      set by the environment activation (required)
:: PY_FREETHREADING:  yes/no, selects the free-threading specific assertions
:: PY_INTERP_DEBUG:   yes/no, consumed by recipe/run_test.py
:: openssl:           openssl major.minor from .ci_support/<CONFIG>.yaml, consumed by run_test.py
:: tk:                tk major.minor from .ci_support/<CONFIG>.yaml, consumed by run_test.py
:: RUN_CMAKE_TEST:    1/0 (default 1), the cmake test needs a working MSVC ARM64 toolchain
:: TEST_RESULT_FILE:  optional, a file that is deleted on entry and only written
::                    once every test has passed. Callers that cannot rely on the
::                    exit code of their launcher can check for it instead.

echo on
setlocal enableextensions enabledelayedexpansion

:: Directory holding this script, i.e. the recipe directory (with trailing \).
set "RECIPE_DIR=%~dp0"

:: TEST_PREFIX acts as a fallback for runners where the launcher does not
:: export CONDA_PREFIX into the child process.
if "%CONDA_PREFIX%" == "" if not "%TEST_PREFIX%" == "" set "CONDA_PREFIX=%TEST_PREFIX%"
if "%CONDA_PREFIX%" == "" (
    echo ERROR: neither CONDA_PREFIX nor TEST_PREFIX is set;
    echo run this script inside an activated test environment
    exit /b 1
)
set "PREFIX=%CONDA_PREFIX%"
:: Make sure the interpreter under test is the one being exercised, not any
:: python that happens to be earlier on PATH.
if not exist "%PREFIX%\python.exe" (
    echo ERROR: no python.exe in %PREFIX%
    exit /b 1
)
set "PATH=%PREFIX%;%PREFIX%\Library\bin;%PREFIX%\Scripts;%PATH%"
if "%PY_FREETHREADING%" == "" set "PY_FREETHREADING=no"
if "%PY_INTERP_DEBUG%" == "" set "PY_INTERP_DEBUG=no"
if "%RUN_CMAKE_TEST%" == "" set "RUN_CMAKE_TEST=1"
if not "%TEST_RESULT_FILE%" == "" if exist "%TEST_RESULT_FILE%" del /Q "%TEST_RESULT_FILE%"

:: ---------------------------------------------------------------------------
:: Sanity checks that are specific to this job: the whole point of running on
:: a windows-11-arm runner is that we exercise a native ARM64 interpreter.
:: ---------------------------------------------------------------------------
call :start_group "Verifying we are running natively on ARM64"
if /i not "%PROCESSOR_ARCHITECTURE%" == "ARM64" (
    echo ERROR: expected PROCESSOR_ARCHITECTURE=ARM64, got "%PROCESSOR_ARCHITECTURE%"
    exit /b 1
)
python -c "import platform, struct, sys; m = platform.machine(); print('machine:', m); print('pointer size:', struct.calcsize('P')); sys.exit(0 if m.upper() == 'ARM64' else 'ERROR: python reports non-ARM64 machine: ' + m)"
if !errorlevel! neq 0 exit /b !errorlevel!
python -c "import sysconfig, sys; p = sysconfig.get_platform(); print('sysconfig platform:', p); sys.exit(0 if 'arm64' in p else 'ERROR: unexpected sysconfig platform: ' + p)"
if !errorlevel! neq 0 exit /b !errorlevel!
python -c "import sys, sysconfig; ft = bool(sysconfig.get_config_var('Py_GIL_DISABLED')); want = '%PY_FREETHREADING%' == 'yes'; print('Py_GIL_DISABLED:', ft); sys.exit(0 if ft == want else 'ERROR: free-threading mismatch, expected %PY_FREETHREADING%')"
if !errorlevel! neq 0 exit /b !errorlevel!
call :end_group

:: ---------------------------------------------------------------------------
:: Stage the recipe test files the way conda-build would, so that the relative
:: paths used by the meta.yaml commands (tests/..., run_test.py) resolve.
:: meta.yaml test/files: tests/cmake/*, tests/cython/*, tests/prefix-replacement/*, run_test.py
:: ---------------------------------------------------------------------------
call :start_group "Staging recipe test files"
set "TEST_WORK_DIR=%CONDA_PREFIX%\..\test_tmp_%PY_FREETHREADING%"
if exist "%TEST_WORK_DIR%" rd /S /Q "%TEST_WORK_DIR%"
mkdir "%TEST_WORK_DIR%"
if !errorlevel! neq 0 exit /b !errorlevel!
copy /Y "%RECIPE_DIR%run_test.py" "%TEST_WORK_DIR%\" >nul
if !errorlevel! neq 0 exit /b !errorlevel!
xcopy /E /I /Y "%RECIPE_DIR%tests" "%TEST_WORK_DIR%\tests" >nul
if !errorlevel! neq 0 exit /b !errorlevel!
cd /D "%TEST_WORK_DIR%"
if !errorlevel! neq 0 exit /b !errorlevel!
echo Test working directory: %CD%
call :end_group

:: ===========================================================================
:: output: python -- test/commands from recipe/meta.yaml, `# [win]` subset
:: ===========================================================================
call :start_group "Dumping environment"
set
call :end_group

call :start_group "python -V / pydoc -h"
python -V
if !errorlevel! neq 0 exit /b !errorlevel!
pydoc -h
if !errorlevel! neq 0 exit /b !errorlevel!
call :end_group

call :start_group "ensurepip"
set "PIP_NO_BUILD_ISOLATION=False"
set "PIP_NO_DEPENDENCIES=True"
set "PIP_IGNORE_INSTALLED=True"
set "PIP_NO_INDEX=True"
set "PIP_CACHE_DIR=%CONDA_PREFIX%/pip_cache"
set "TEMP=%CONDA_PREFIX%/tmp"
if not exist "%TEMP%" mkdir "%TEMP%"
python -Im ensurepip --upgrade --default-pip
if !errorlevel! neq 0 exit /b !errorlevel!
call :end_group

call :start_group "zoneinfo / tzdata"
:: tzdata/zoneinfo test that will need the tzdata package to pass
python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
if !errorlevel! neq 0 exit /b !errorlevel!
call :end_group

call :start_group "venv + ctypes"
python -m venv test-venv
if !errorlevel! neq 0 exit /b !errorlevel!
test-venv\Scripts\python.exe -c "import ctypes"
if !errorlevel! neq 0 exit /b !errorlevel!
call :end_group

call :start_group "Checking installed layout"
:: Determine the ABI version tag (e.g. 315) from the interpreter under test
for /f "delims=" %%i in ('python -c "import sys; print('%%s%%s' %% sys.version_info[:2])"') do set "VER2ND=%%i"
if "!VER2ND!" == "" (
    echo ERROR: could not determine the python version tag
    exit /b 1
)
echo Python ABI version tag: !VER2ND!
if /i "%PY_FREETHREADING%" == "yes" (
    if not exist %PREFIX%\libs\python3t.lib exit 1
    if not exist %PREFIX%\libs\python!VER2ND!t.lib exit 1
) else (
    if not exist %PREFIX%\libs\python3.lib exit 1
    if not exist %PREFIX%\libs\python!VER2ND!.lib exit 1
)
:: https://github.com/conda-forge/python-feedstock/issues/384
if exist %PREFIX%\Scripts\pydoc exit 1
if exist %PREFIX%\Scripts\idle exit 1
if not exist %PREFIX%\Scripts\pydoc-script.py exit 1
if not exist %PREFIX%\Scripts\idle-script.py exit 1
if not exist %PREFIX%\Scripts\idle.exe exit 1
if not exist %PREFIX%\Scripts\pydoc.exe exit 1
if not exist %PREFIX%\include\pyconfig.h exit 1
call :end_group

:: TODO: use the new FindPython3 which supports freethreading
:: Flat gotos rather than an if/else block: see the note on :run_cmake_test.
if /i not "%RUN_CMAKE_TEST%" == "1" goto :skip_cmake_disabled
if /i not "%PY_FREETHREADING%" == "no" goto :skip_cmake_freethreading
call :run_cmake_test
if !errorlevel! neq 0 exit /b !errorlevel!
goto :after_cmake
:skip_cmake_disabled
echo Skipping the cmake test: RUN_CMAKE_TEST=%RUN_CMAKE_TEST%
goto :after_cmake
:skip_cmake_freethreading
echo Skipping the cmake test: FindPythonLibs does not support free-threading builds
:after_cmake

call :start_group "run_test.py"
python run_test.py
if !errorlevel! neq 0 exit /b !errorlevel!
call :end_group

call :start_group "ctypes CFUNCTYPE"
:: Test for segfault on osx-64 with libffi=3.4, see https://bugs.python.org/issue44556
python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
if !errorlevel! neq 0 exit /b !errorlevel!
call :end_group

:: ===========================================================================
:: output: libpython-static -- recipe/build_static.bat is empty and every
:: test command for this output is `# [unix]`/`# [osx]` only, so on Windows
:: there is nothing to assert beyond the package installing cleanly.
:: ===========================================================================
call :start_group "libpython-static"
dir /B "%PREFIX%\conda-meta\libpython-static-*.json" >nul 2>nul
if !errorlevel! neq 0 (
    echo ERROR: libpython-static is not installed in %PREFIX%
    exit /b 1
)
echo libpython-static is installed ^(no Windows test commands in meta.yaml^)
call :end_group

echo All native win-arm64 tests passed
if not "%TEST_RESULT_FILE%" == "" echo passed> "%TEST_RESULT_FILE%"
exit /b 0

:: ---------------------------------------------------------------------------
:: The cmake test, as a subroutine rather than inline in an `if (...)` block:
:: cmd parses such a block in full before running it, so a ")" anywhere inside
:: -- including in a "::" comment -- terminates it early, and a "::" line is
:: parsed as a drive-relative path ("The system cannot find the drive
:: specified.") instead of a label. Neither problem exists in a subroutine.
:: ---------------------------------------------------------------------------
:run_cmake_test
call :start_group "cmake FindPythonInterp/FindPythonLibs"
pushd tests\cmake
if !errorlevel! neq 0 exit /b !errorlevel!

:: meta.yaml passes the plain "X.Y.Z" recipe version here. Derive the same shape
:: from the interpreter, since platform.python_version() yields "3.15.0rc1",
:: which find_package() cannot parse as a version.
for /f "delims=" %%i in ('python -c "import sys; print('%%s.%%s.%%s' %% sys.version_info[:3])"') do set "PY_FULL_VER=%%i"
if "!PY_FULL_VER!" == "" (
    echo ERROR: could not determine the full python version
    exit /b 1
)

:: FindPythonInterp searches for python3.15/python3 first and only falls back to
:: a plain "python" pass if that finds nothing. A conda prefix has no
:: python3.exe, so under conda-build the fallback picks up the interpreter under
:: test -- but the windows-11-arm image has C:\hostedtoolcache\windows\Python\
:: <ver>\arm64\python3.exe on PATH, which wins the first pass and then fails the
:: version check ("Found unsuitable version 3.13.15"). Point cmake at the
:: interpreter explicitly; FindPythonLibs takes it as its hint in turn.
:: cmake wants forward slashes in a path it stores in the cache.
set "PY_EXE_CMAKE=%PREFIX:\=/%/python.exe"
echo Requesting PY_VER=!PY_FULL_VER! with PYTHON_EXECUTABLE=!PY_EXE_CMAKE!
cmake -GNinja -DPY_VER=!PY_FULL_VER! "-DPYTHON_EXECUTABLE=!PY_EXE_CMAKE!" --debug-find --trace --debug-output --debug-trycompile .
if !errorlevel! neq 0 exit /b !errorlevel!
popd
call :end_group
exit /b 0

:: Logging subroutines

:start_group
if /i "%CI%" == "github_actions" (
    echo ::group::%~1
    exit /b
)
echo %~1
exit /b

:end_group
if /i "%CI%" == "github_actions" (
    echo ::endgroup::
    exit /b
)
exit /b
